window.__researchCheckResult = null;
(async () => {
  const checks = [];
  const assert = (condition, name) => { if (!condition) throw new Error(name); checks.push(name); };
  const wait = async (predicate) => {
    const deadline = Date.now() + 8000;
    while (!predicate()) { if (Date.now() > deadline) throw new Error("界面等待超时"); await new Promise(resolve => setTimeout(resolve, 40)); }
  };
  const stocks = () => [...document.querySelectorAll(".stock")];
  const form = document.getElementById("researchForm");
  const date = document.getElementById("researchDate");
  const code = document.getElementById("researchCode");
  const today = date.value;
  await wait(() => stocks().length === 2);
  assert(stocks().every(stock => !stock.open), "逐股默认收起");
  assert(document.querySelectorAll(".metric b")[2].textContent === "1", "静默命中单独统计");
  assert(document.querySelectorAll(".metric b")[3].textContent === "0", "静默命中不计正式提示");
  assert(document.querySelectorAll(".metric b")[4].textContent === "1", "早封结构实验单独统计");
  stocks()[0].querySelector("summary").click();
  await wait(() => stocks()[0].querySelectorAll("tbody tr").length === 50);
  assert(!stocks()[1].open, "展开一只不展开另一只");
  assert(stocks()[0].textContent.includes("10:01:00"), "首次触发保留真实采样时间");
  assert(stocks()[0].textContent.includes("源时间：未提供"), "不把资金获取时间冒充源时间");
  stocks()[0].querySelector(".stock-samples button").click();
  await wait(() => stocks()[0].querySelectorAll("tbody tr").length === 56);
  assert(!stocks()[0].querySelector(".stock-samples button"), "分页无重复且末页停止");
  stocks()[0].querySelector("summary").click();
  stocks()[1].querySelector("summary").click();
  await wait(() => stocks()[1].dataset.loaded === "1");
  assert(!stocks()[0].open && stocks()[1].open, "独立展开收起");
  assert(stocks()[1].textContent.includes("不与原实验凑次数"), "结构实验次数与原实验隔离展示");
  code.value = "600002"; form.requestSubmit();
  await wait(() => stocks().length === 1 && stocks()[0].dataset.code === "600002");
  assert(stocks()[0].open, "过滤后保留该股票展开偏好");
  code.value = "600999"; form.requestSubmit();
  await wait(() => !!document.querySelector(".empty"));
  assert(document.querySelector(".empty").textContent.includes("不生成历史假数据"), "空记录明确提示而不补造");
  code.value = ""; date.value = "2026-08-28"; form.requestSubmit();
  await wait(() => !!document.querySelector(".empty"));
  assert(document.querySelectorAll(".metric b")[0].textContent === "0", "历史日期没有伪造采样");
  const originalFetch = window.fetch;
  window.fetch = async () => ({ok:false, json:async () => ({error:"隔离测试：研究记录读取失败"})});
  form.requestSubmit();
  await wait(() => document.getElementById("researchStatus").className === "error");
  assert(document.getElementById("researchStatus").textContent.includes("研究记录读取失败"), "接口错误可见且不展示旧结果");
  window.fetch = originalFetch;
  date.value = today; form.requestSubmit();
  await wait(() => stocks().length === 2);
  assert(!stocks()[0].open && stocks()[1].open, "跨查询逐股偏好独立保留");
  assert(typeof window.BoardAlerts === "undefined", "研究页不接入预警引擎");
  const requests = performance.getEntriesByType("resource").filter(entry => entry.initiatorType === "fetch");
  assert(requests.length > 0 && requests.every(entry => new URL(entry.name).pathname === "/api/board-research"), "查询页仅访问只读接口不触发扫描");
  assert(!document.querySelector(".board-alert-window"), "无弹窗或交易入口");
  const recording = document.createElement("p");
  recording.id = "researchRecordingStatus";
  document.body.append(recording);
  window.BoardResearchStatus({available:false,message:"写入失败，静默研究暂停"});
  assert(recording.textContent.includes("写入失败"), "主页写入失败提示可见");
  window.BoardResearchStatus({available:true,recording:true,sample_count:0,shadow_stock_count:0,last_collected_at:null});
  assert(recording.textContent.includes("最近采样 暂无"), "零采样不显示空时间值");
  window.BoardResearchStatus();
  assert(recording.textContent.includes("重启后端"), "旧后端明确提示启用方法");
  recording.remove();
  return {passed:checks.length, checks};
})().then(result => { window.__researchCheckResult = result; }).catch(error => { window.__researchCheckResult = {error: error.message}; });
