const assert = require("node:assert/strict");
const { keyFor, createStore, riskLabel, STORAGE_KEY } = require("../web/stock-card-details.js");
const memory = new Map();
const storage = { getItem: (key) => memory.get(key), setItem: (key, value) => memory.set(key, value) };
const a = keyFor("2026-08-31", "auction", "600001");
const b = keyFor("2026-08-31", "auction", "600002");
const live = keyFor("2026-08-31", "live", "600001");
const nextDate = keyFor("2026-09-01", "auction", "600001");
const store = createStore(storage);
assert.equal(store.isOpen(a), false);
store.remember(a, true);
assert.equal(store.isOpen(a), true);
assert.equal(store.isOpen(b), false);
assert.equal(store.isOpen(live), false);
assert.equal(store.isOpen(nextDate), false);
store.remember(b, true);
store.remember(a, false);
assert.equal(store.isOpen(a), false);
assert.equal(store.isOpen(b), true);
const reloaded = createStore(storage);
assert.equal(reloaded.isOpen(a), false);
assert.equal(reloaded.isOpen(b), true);
assert.equal(keyFor("", "auction", "600001"), null);
assert.equal(keyFor("2026-08-31", "auction", '600001" onclick="bad'), null);
store.remember(null, true);
assert.equal(store.isOpen(null), false);
storage.setItem(STORAGE_KEY, "invalid");
assert.equal(createStore(storage).isOpen(b), false);
storage.setItem(STORAGE_KEY, JSON.stringify({ invalid: true }));
assert.equal(createStore(storage).isOpen(b), false);
const unavailable = createStore({ getItem() { throw new Error("blocked"); }, setItem() { throw new Error("blocked"); } });
unavailable.remember(a, true);
assert.equal(unavailable.isOpen(a), true);
unavailable.remember(a, false);
assert.equal(unavailable.isOpen(a), false);
assert.equal(riskLabel({ failed_board: true }), "炸板风险");
assert.equal(riskLabel({ corporate_event_risk: { level: "high", label: "重组风险" } }), "重组风险");
assert.equal(riskLabel({ regulatory_risk: { level: "high" } }), "异动高风险");
assert.equal(riskLabel({}), "");
console.log("stock-card-details: independent state, reload, dates, storage fallback and risk labels OK");
